### ISSUE TITLE
packaging

### ISSUE THREAD

**Issue by MichaelMure** [MichaelMure/TotallyNotArbore#25]
There is already some packaging that comes from the electron boilerplate I used, but someone need to review it.

A good things to have would be:
- windows: installer
- mac: dmg package
- linux: .deb, .rpm and flatpak package

Maybe use electron-forge ?

**Comment by MichaelMure** [comment]
@hyeyoungseo can you try `npm run package` on mac and try an installation ?

**Comment by hyeyoungseo** [comment]
1. I got 'Arbore-0.0.0.dmg' file in the directory - /TotallyNotArbore/release/mac.
2. It's installed very well and works good except that 'logo.svg' image is not shown on the application.

**Comment by MichaelMure** [comment]
@hyeyoungseo Thank you ! 👍 

We have to find out why this image doesn't show.

**Comment by MichaelMure** [comment]
It also happen with the linux packaging

**Comment by MichaelMure** [comment]
So the logo should appear on the login screen with the commit https://github.com/MichaelMure/TotallyNotArbore/commit/d413ad72a1f7bb604a157f062057fe9bab57acf0

It still doesn't appear on the splashscreen, probably because of a webpack obscur configuration. On a side note, with a packaged version, the loading of the application is too fast to actually notice the splashscreen. Well ... :man_shrugging:

**Comment by MichaelMure** [comment]
So, with https://github.com/MichaelMure/TotallyNotArbore/commit/7bd8301942adbb065002aa44a25ce19e4ed318b9 I'm able to package from linux for linux and windows (32 and 64bits).

I can't cross-compile for MacOS because apple is apple and you need to package from a running mac.

The installer in windows is weird, it's a one-step installer that run the app on exit, so it's not obvious that the app is actually installed.

**Comment by MichaelMure** [comment]
It works now, at least on my machine o/
