### ISSUE TITLE
Contact Page not opening 

### ISSUE THREAD

**Issue by karthik-ir** [MichaelMure/TotallyNotArbore#34]
Error on trying to open contact 
`warning.js:36 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `ContactDetail`.`

**Comment by MichaelMure** [comment]
Can you confirm it was due to a package not properly installed locally ?

**Comment by karthik-ir** [comment]
This was fixed on npm update within the app/ . For some reason IPFS connector is not updated from the root package.json.
